### ISSUE TITLE
kræsj

### ISSUE THREAD

**Issue by boutros** [digibib/koha-indexer#1]
```
2017/03/28 19:25:59 Persisting to disk...
panic: runtime error: index out of range
goroutine 33 [running]:
main.record.sameAs(0x114834, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, 0xc428f1ace0, 0x2, 0x2, ...)
	/home/boutros/src/github.com/boutros/koha-indexer/collector.go:383 +0x1ed
main.collector.persistUpdated.func1(0xc429682620, 0x719580, 0xc429682620)
	/home/boutros/src/github.com/boutros/koha-indexer/collector.go:80 +0x330
github.com/boltdb/bolt.(*DB).Update(0xc42009a680, 0xc420087380, 0x0, 0x0)
	/home/boutros/src/github.com/boltdb/bolt/db.go:552 +0x9f
main.collector.persistUpdated(0xc42009a680, 0xc4200e22c0, 0xdf8475800, 0xc420087638, 0xed06cafbe, 0x6000ae0, 0x8674e0, 0x0, 0x0, 0x2d, ...)
	/home/boutros/src/github.com/boutros/koha-indexer/collector.go:133 +0xdd
main.collector.run(0xc42009a680, 0xc4200e22c0, 0xdf8475800, 0xc42010a800, 0x14, 0xc4200ae688)
	/home/boutros/src/github.com/boutros/koha-indexer/collector.go:328 +0x10b1
created by main.main
	/home/boutros/src/github.com/boutros/koha-indexer/main.go:56 +0x55d

```

**Comment by boutros** [comment]
https://github.com/digibib/koha-indexer/commit/4657ebf7629114b49aa13b6c1d10ed911225bc8f
